/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/project/[id]/active`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/project/[id]/details`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/project/[id]/pdf`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]/followers`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]/following`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/project/[id]/active`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/project/[id]/details`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/project/[id]/pdf`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/user/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/user/[id]/followers`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/user/[id]/following`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/edit-profile${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | `/project/${Router.SingleRoutePart<T>}/active${`?${string}` | `#${string}` | ''}` | `/project/${Router.SingleRoutePart<T>}/details${`?${string}` | `#${string}` | ''}` | `/project/${Router.SingleRoutePart<T>}/pdf${`?${string}` | `#${string}` | ''}` | `/user/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/user/${Router.SingleRoutePart<T>}/followers${`?${string}` | `#${string}` | ''}` | `/user/${Router.SingleRoutePart<T>}/following${`?${string}` | `#${string}` | ''}` | { pathname: `/project/[id]/active`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/project/[id]/details`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/project/[id]/pdf`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]/followers`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[id]/following`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
